### ISSUE TITLE
[Bug] Backtracking creates dots on end of lines

### ISSUE THREAD

**Issue by sandorex** [steveruizok/perfect-freehand#48]
As i mentioned in https://github.com/excalidraw/excalidraw/issues/4802#issuecomment-1145413251

Moving cursor in opposite direction while drawing makes these weird dots, much more common on wacom tablet for some reason

freehand playground
![image](https://user-images.githubusercontent.com/18004075/171749987-ad382148-f456-4d14-9abe-2627978a3a86.png)

freehand playground but using the mouse
![image](https://user-images.githubusercontent.com/18004075/171750147-737ae648-6a5a-4a4d-bc26-47552ec05de3.png)

**Comment by TodePond** [comment]
Also found this - screenshot from the playground: 
![image](https://user-images.githubusercontent.com/15892272/185923997-480aa018-d20f-4401-bbf4-0db174aa97be.png)

Quite a small issue I think, because it's generally quite hard to reproduce+notice, but I've been using perfect-freehand in an app where the stroke bounces back a bit at the end, which reliably causes it quite a lot: 
![image](https://user-images.githubusercontent.com/15892272/185924309-01231c44-05bf-4103-9b99-119f0b12ebba.png)

**Comment by TodePond** [comment]
Potentially related to this part? https://github.com/steveruizok/perfect-freehand/blob/main/packages/perfect-freehand/src/getStrokeOutlinePoints.ts#L210-L239

Answer: I don't think so! I disabled that section of code and it's still reproducible: 
![image](https://user-images.githubusercontent.com/15892272/185930156-4f57605c-ac09-4a2b-9b31-5a8bfd77bb12.png)

I'll look elsewhere!

**Comment by TodePond** [comment]
Potentially related to it "flipping over"? 
![image](https://user-images.githubusercontent.com/15892272/185930954-da880307-55a5-409b-8f99-220cb95bb72b.png)

**Comment by TodePond** [comment]
You can see it cross over for a frame or two: 
![GIF 22-08-2022 14-20-49](https://user-images.githubusercontent.com/15892272/185931192-1d916186-0790-47cb-9e54-55321d267ece.gif)

**Comment by TodePond** [comment]
Making the `Handle sharp corners` code run based on previous dot-product instead of next dot-product helped in some cases:

Before:
![image](https://user-images.githubusercontent.com/15892272/185936528-bf523f52-cf28-453e-8b68-ad0642f0d736.png)

After: 
![image](https://user-images.githubusercontent.com/15892272/185936405-070a7801-403c-4d3c-9a6c-7493516196ad.png)

**Comment by TodePond** [comment]
Ok and if I make it check `nextDpr` as well as `prevDpr` it seems to fix all those cases:
![image](https://user-images.githubusercontent.com/15892272/185938560-6c8d96a7-18ce-4ac4-988b-087acbd179fc.png)

Still some issues going on though.

**Comment by TodePond** [comment]
Ok so now we get this issue:
![image](https://user-images.githubusercontent.com/15892272/185939681-bdf06933-dc8f-4bba-aff5-746c51e8b3ce.png)

What's happening?
Answer: After a stroke does a sharp corner, it keeps doing sharp corners every point. This is because it now looks for sharp corners based on the next point AND the previous point. It can end up detecting a sharp corner twice, and then keeps on flip-flopping. Maybe we could keep some state to make sure it doesn't do the same sharp corner twice...

It works!
![image](https://user-images.githubusercontent.com/15892272/185940115-d73f0653-33c3-40de-81aa-602f31889f4d.png)

And the fix still works!
![image](https://user-images.githubusercontent.com/15892272/185940256-a51f75fe-8895-45fe-b4f9-86ff592e4264.png)

I'm gonna clean up the code and do a pull request I think.

**Comment by steveruizok** [comment]
Awesome work!

**Comment by sandorex** [comment]
Nice work, ill close this now
